### ISSUE TITLE
Possible to call Azure FHIR API using MSAL authentication process

### ISSUE THREAD

**Issue by RahulKate** [microsoft/fhir-server-samples#90]
I am using MSAL daemon server authentication mechanism to call FHIR API using example specified in below link,
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2

I tried with sample application, able to retrieve access token using MSAL library but its giving **forbidden error** while calling FHIR API from daemon process, Is it possible to access FHIR API using daemon application?

![image](https://user-images.githubusercontent.com/13742253/91970714-aecde480-ed35-11ea-9458-4a6bac337dbf.png)

Its mentioned in MSAL sample application that we need application permission in order to access API, let me know if it is possible to provide application permission for FHIR API from app registration, currently application permission for Azure Healthcare API is disabled and not able to add as shown in below image,

![image](https://user-images.githubusercontent.com/13742253/91970409-42eb7c00-ed35-11ea-94f3-15ab483551e0.png)

**Comment by hansenms** [comment]
I am assuming that by "daemon server authentication" you mean service to service authorization and so you are using "client credentials flow" (in Azure AD parlance). 

It is not exactly clear from this whether you are getting a `401` or `403` error code, but it sounds like `403`. So if that is the case, the reason is probably that the service principal that you are getting a token for does not have access to the FHIR API. Did you give that service principal access? And is this specifically related to this fhir-server-samples repo or is this a general question related?

**Comment by RahulKate** [comment]
@hansenms 

Yeah, you are right about below points,

1) Error Code : 403, Forbidden
2) Using Client Credential Flow, sample flow as,

![image](https://user-images.githubusercontent.com/13742253/92006646-a17b1f00-ed62-11ea-9fea-9443ce3388bb.png)

But I am trying to access FHIR API from daemon process, and authentication mechanism is MSAL latest library, I will check details of service principals....

MSAL team is looking for someone from Azure Healthcare API's, please have a look into below git hub issue,

https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/issues/89

**Comment by hansenms** [comment]
If you are getting a 403, it means that the service principal (the app registration) does not have access to the FHIR API. You need to grant it access. How you do that depends on whether you are using [Azure RBAC](https://docs.microsoft.com/en-us/azure/healthcare-apis/configure-azure-rbac) or [Local RBAC](https://docs.microsoft.com/en-us/azure/healthcare-apis/configure-local-rbac).

You need to take a look at your token (e.g. with https://jtw.ms) and figure out what the `oid` claim is. That is the object id of the identity that you need to grant access. It is slightly confusing because there is both and app id and an object id, but the object id is what matters. If you are using local RBAC, you simply add that `oid` to the list of allowed object ids per instructions above. If you are using Azure RBAC, follow the instructions there.

@ginalee-dotcom is on the Healthcare APIs team and can assist.

**Comment by RahulKate** [comment]
Issue resolved by following steps for Azure RBAC, I need to assign FHIR roles to desired app to access FHIR API from daemon or web api, I assigned role to my user name instead of App...

https://docs.microsoft.com/en-us/azure/healthcare-apis/configure-azure-rbac
