### ISSUE TITLE
AzureAd Module is not Cross Platform

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/fhir-server-samples#96]
**Overview**
I'm currently going through the [FHIR OpenHack](https://github.com/microsoft/OpenHack-FHIR) on my Mac. The first issue I run into is the inability to use `Connect-AzureAd` after installing the `AzureAd` module. After some quick research, I see the current module published in `PsGallery` is Windows only due to .NET Framework dependencies.

**Workaround**
I was able to find a workaround [here](https://github.com/PowerShell/PowerShell/issues/5274#issuecomment-556501122). For a short term fix, should there be some directions for users not on Windows? This would open up the repo to a much larger user base, even if this information is hidden from the main README.
```pwsh
Register-PackageSource -Trusted -ProviderName 'PowerShellGet' -Name 'Posh Test Gallery' -Location https://www.poshtestgallery.com/api/v2/
Install-Module -Name AzureAD.Standard.Preview
Import-Module AzureAD.Standard.Preview
```

**Long Term Solution**
Long term I think syncing with the AzureAD product group and determining if they will be releasing an updates, non-private preview version of this module.
- If so, this will be an easy long term fix; just use the preview until the mature version is released
- If not, moving away from the `AzureAd` module as it's not being updated

**Comment by jananivMS** [comment]
Commenting here as I ran into the same issue. Also, expanding beyond Mikael's comment, it would be great to make the installation mechanisms cross platform.

**Comment by ginalee-dotcom** [comment]
Thank you for this insight! We are working on making it cross-platform. AzureAD module is no longer supported on MacOS or Linux, as it does not work with PowerShell Core. We are looking into ways to make this samples repo deployable without using AzureAD, and perhaps providing Azure CLI deployment option. Will keep you updated on this.

**Comment by nmiodice** [comment]
Note: I created a PR in the open hack repository to add the workaround (in addition to another x-platform issue I ran into): https://github.com/microsoft/OpenHack-FHIR/pull/11

**Comment by mikenri** [comment]
Can you update this feedback post with a status update?
The last update is from 2019 which stated that it should be available within a couple of weeks. 

https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/33502754-linux-compatibility-for-azuread-powershell-module

**Comment by nmiodice** [comment]
@mikenri, who is the "you" in your comment?

**Comment by ginalee-dotcom** [comment]
Apologies for the delayed reply. **Yesterday I was able to deploy the environment successfully on my Mac OS**, and was able to run`Connect-AzureAd` command without any issue. I did not need to use any workarounds such as the one provided above. I used `powershell-7.1.0-osx-x64.pkg` and `dotnet-sdk-3.1.404-osx-x64.pkg`, and version `0.1.599.7` of `AzureAD.Standard.Preview`. 
@mikenri We are not in charge of Azure Active Directory, we are leveraging it for our product. So the feedback should be provided by Azure Active Directory team. However, I will make sure to update our repo with the latest information on the Linux/MacOS compatibility for AzureAD Powershell Module. Meanwhile, I will keep working on the deployment option that uses Azure CLI, so that we could possibly opt out from dealing with AzureAD platform compatibility issues.
I am closing this issue, and will update our repo documentation once the alternative deployment options are complete. Feel free to re-open with any follow-up questions!
